edition = "2021"
tab_spaces = 4
max_width = 150
struct_lit_single_line = true
hard_tabs = false
fn_single_line = true
overflow_delimited_expr = true
newline_style = "Auto"
use_small_heuristics = "Max"
fn_args_layout = "Compressed"
fn_params_layout = "Compressed"
